### 게시판 목록 조회
GET /board/list
Host: localhost:8080
Content-Type: application/json

### 게시판 등록
POST /board/create HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
  "title" : "title{{$randomInt}}",
  "content" : "{{$random.alphanumeric(10)}}",
  "regType" : "User",
  "regName" : "name{{$random.alphabetic(3)}}"
}

### 사용자 등록
POST /user/create HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
  "userId" : "id{{$randomInt}}",
  "userName" : "name{{$random.alphabetic(3)}}",
  "userPassword" : "1234",
  "userAuthority": "ROLE_USER"
}